// frontend/src/components/Members.vue
<template>
  <div class="page-container">
    <v-row>
      <v-col cols="12">
        <v-card class="cyberpunk-card mb-4">
          <v-card-title class="neon-text">
            <v-icon icon="mdi-account-group" class="neon-icon mr-2"></v-icon>
            Member Management
            <v-spacer></v-spacer>
            <v-btn color="primary" @click="showAddDialog = true" class="neon-btn">
              <v-icon left>mdi-plus</v-icon>
              Add Member
            </v-btn>
          </v-card-title>
        </v-card>
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12">
        <v-card class="cyberpunk-card">
          <v-card-text>
            <v-data-table
              :headers="headers"
              :items="members"
              class="cyberpunk-table"
              :loading="loading"
            >
              <template v-slot:item.actions="{ item }">
                <v-btn icon size="small" @click="editMember(item)" class="neon-icon">
                  <v-icon>mdi-pencil</v-icon>
                </v-btn>
                <v-btn icon size="small" @click="deleteMember(item)" color="error" class="neon-icon">
                  <v-icon>mdi-delete</v-icon>
                </v-btn>
              </template>
            </v-data-table>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <!-- Add/Edit Member Dialog -->
    <v-dialog v-model="showAddDialog" max-width="600px">
      <v-card class="cyberpunk-card">
        <v-card-title class="neon-text">
          {{ editingMember ? 'Edit Member' : 'Add New Member' }}
        </v-card-title>
        <v-card-text>
          <v-form @submit.prevent="saveMember">
            <v-text-field
              v-model="memberForm.name"
              label="Name"
              required
              class="mb-3"
            ></v-text-field>
            <v-text-field
              v-model="memberForm.age"
              label="Age"
              type="number"
              required
              class="mb-3"
            ></v-text-field>
            <v-select
              v-model="memberForm.gender"
              :items="['Male', 'Female', 'Other']"
              label="Gender"
              required
              class="mb-3"
            ></v-select>
            <v-text-field
              v-model="memberForm.contact"
              label="Contact"
              required
              class="mb-3"
            ></v-text-field>
            <v-btn type="submit" color="primary" class="neon-btn">
              {{ editingMember ? 'Update' : 'Add' }} Member
            </v-btn>
          </v-form>
        </v-card-text>
      </v-card>
    </v-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

// Data
const members = ref([])
const loading = ref(false)
const showAddDialog = ref(false)
const editingMember = ref(null)

const headers = [
  { title: 'ID', key: 'id' },
  { title: 'Name', key: 'name' },
  { title: 'Age', key: 'age' },
  { title: 'Gender', key: 'gender' },
  { title: 'Contact', key: 'contact' },
  { title: 'Actions', key: 'actions', sortable: false }
]

const memberForm = ref({
  name: '',
  age: '',
  gender: '',
  contact: ''
})

// Methods
const fetchMembers = async () => {
  loading.value = true
  try {
    const response = await fetch('http://localhost:8080/members')
    if (response.ok) {
      members.value = await response.json()
    } else {
      // Fallback to mock data if backend is not running
      console.warn('Backend not available, using mock data')
      members.value = [
        { id: 1, name: 'John Doe', age: 30, gender: 'Male', contact: 'john@example.com' },
        { id: 2, name: 'Jane Smith', age: 25, gender: 'Female', contact: 'jane@example.com' },
        { id: 3, name: 'Bob Johnson', age: 35, gender: 'Male', contact: 'bob@example.com' }
      ]
    }
  } catch (error) {
    console.error('Error fetching members:', error)
    // Fallback to mock data
    members.value = [
      { id: 1, name: 'John Doe', age: 30, gender: 'Male', contact: 'john@example.com' },
      { id: 2, name: 'Jane Smith', age: 25, gender: 'Female', contact: 'jane@example.com' },
      { id: 3, name: 'Bob Johnson', age: 35, gender: 'Male', contact: 'bob@example.com' }
    ]
  } finally {
    loading.value = false
  }
}

const saveMember = async () => {
  try {
    let response
    if (editingMember.value) {
      // Update member via API
      response = await fetch(`http://localhost:8080/members/${editingMember.value.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(memberForm.value)
      })
    } else {
      // Add new member via API
      response = await fetch('http://localhost:8080/members', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(memberForm.value)
      })
    }

    if (response.ok) {
      // Reset form and close dialog
      memberForm.value = { name: '', age: '', gender: '', contact: '' }
      editingMember.value = null
      showAddDialog.value = false

      // Refresh members list
      await fetchMembers()
    } else {
      console.error('Failed to save member:', response.statusText)
      // For demo purposes, still update the UI
      memberForm.value = { name: '', age: '', gender: '', contact: '' }
      editingMember.value = null
      showAddDialog.value = false
      await fetchMembers()
    }
  } catch (error) {
    console.error('Error saving member:', error)
    // For demo purposes, still update the UI
    memberForm.value = { name: '', age: '', gender: '', contact: '' }
    editingMember.value = null
    showAddDialog.value = false
    await fetchMembers()
  }
}

const editMember = (item) => {
  editingMember.value = item
  memberForm.value = { ...item }
  showAddDialog.value = true
}

const deleteMember = async (item) => {
  if (confirm('Are you sure you want to delete this member?')) {
    try {
      const response = await fetch(`http://localhost:8080/members/${item.id}`, {
        method: 'DELETE'
      })

      if (response.ok) {
        // Refresh members list
        await fetchMembers()
      } else {
        console.error('Failed to delete member:', response.statusText)
        // For demo purposes, still update the UI
        await fetchMembers()
      }
    } catch (error) {
      console.error('Error deleting member:', error)
      // For demo purposes, still update the UI
      await fetchMembers()
    }
  }
}

onMounted(() => {
  fetchMembers()
})
</script>

<style scoped>
.page-container {
  animation: fadeIn 0.5s ease-in;
}

@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}

.cyberpunk-card {
  background: rgba(26, 26, 26, 0.9);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 0, 128, 0.3);
  border-radius: 12px;
  box-shadow: 0 0 20px rgba(255, 0, 128, 0.1);
}

.neon-text {
  color: #00ffff !important;
  text-shadow: 0 0 5px #00ffff;
}

.neon-icon {
  color: #ff0080 !important;
  filter: drop-shadow(0 0 3px #ff0080);
}

.neon-btn {
  background: linear-gradient(45deg, #ff0080, #00ffff) !important;
  color: white !important;
  border: none !important;
}

.cyberpunk-table :deep(.v-data-table-header) {
  background: rgba(255, 0, 128, 0.1);
}

.cyberpunk-table :deep(.v-data-table-header th) {
  color: #00ffff !important;
  font-weight: bold;
}

.cyberpunk-table :deep(.v-data-table-row) {
  transition: all 0.3s ease;
}

.cyberpunk-table :deep(.v-data-table-row:hover) {
  background: rgba(255, 0, 128, 0.1);
  box-shadow: 0 0 10px rgba(255, 0, 128, 0.2);
}

.mr-2 {
  margin-right: 8px;
}

.mb-4 {
  margin-bottom: 16px;
}

.mb-3 {
  margin-bottom: 12px;
}
</style>

// frontend/src/components/Members.jsx
import React, { useEffect, useState } from 'react'
import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'
import Typography from '@mui/material/Typography'
import Button from '@mui/material/Button'
import Table from '@mui/material/Table'
import TableBody from '@mui/material/TableBody'
import TableCell from '@mui/material/TableCell'
import TableHead from '@mui/material/TableHead'
import TableRow from '@mui/material/TableRow'
import Dialog from '@mui/material/Dialog'
import DialogTitle from '@mui/material/DialogTitle'
import DialogContent from '@mui/material/DialogContent'
import DialogActions from '@mui/material/DialogActions'
import TextField from '@mui/material/TextField'
import Select from '@mui/material/Select'
import MenuItem from '@mui/material/MenuItem'
import IconButton from '@mui/material/IconButton'
import EditIcon from '@mui/icons-material/Edit'
import DeleteIcon from '@mui/icons-material/Delete'
import Box from '@mui/material/Box'
import Snackbar from '@mui/material/Snackbar'
import Alert from '@mui/material/Alert'

export default function Members() {
  const [members, setMembers] = useState([])
  const [loading, setLoading] = useState(false)
  const [openDialog, setOpenDialog] = useState(false)
  const [editingMember, setEditingMember] = useState(null)
  const [form, setForm] = useState({ name: '', age: '', gender: '', contact: '' })
  const [snack, setSnack] = useState({ open: false, message: '', severity: 'info' })

  const API_BASE = 'http://localhost:8080/members'

  const showSnack = (message, severity = 'success') => {
    setSnack({ open: true, message, severity })
  }

  const fetchMembers = async () => {
    setLoading(true)
    try {
      const res = await fetch(API_BASE)
      if (!res.ok) throw new Error('Network error')
      const data = await res.json()
      setMembers(data)
    } catch (err) {
      console.warn('Backend not available, using mock data', err)
      setMembers([
        { id: 1, name: 'John Doe', age: 30, gender: 'Male', contact: 'john@example.com' },
        { id: 2, name: 'Jane Smith', age: 25, gender: 'Female', contact: 'jane@example.com' }
      ])
      showSnack('Using fallback data (backend unreachable)', 'warning')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchMembers() }, [])

  const openAdd = () => {
    setEditingMember(null)
    setForm({ name: '', age: '', gender: '', contact: '' })
    setOpenDialog(true)
  }

  const openEdit = (member) => {
    setEditingMember(member)
    setForm({ name: member.name || '', age: member.age || '', gender: member.gender || '', contact: member.contact || '' })
    setOpenDialog(true)
  }

  const saveMember = async () => {
    // basic validation
    if (!form.name) { showSnack('Name is required', 'error'); return }
    try {
      let res
      if (editingMember) {
        res = await fetch(`${API_BASE}/${editingMember.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(form)
        })
      } else {
        res = await fetch(API_BASE, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(form)
        })
      }

      if (res.ok) {
        showSnack(editingMember ? 'Member updated' : 'Member added', 'success')
        setOpenDialog(false)
        setEditingMember(null)
        await fetchMembers()
      } else {
        let errorMessage = 'Save failed'
        try {
          const errorData = await res.json()
          if (errorData.message) {
            errorMessage = errorData.message
          } else if (errorData.violations && errorData.violations.length > 0) {
            // Handle validation violations
            errorMessage = errorData.violations.map(v => v.message).join(', ')
          } else if (errorData.errors && Array.isArray(errorData.errors)) {
            // Alternative error format
            errorMessage = errorData.errors.join(', ')
          }
        } catch (parseError) {
          // If JSON parsing fails, use status text
          errorMessage = `Save failed: ${res.status} ${res.statusText}`
        }
        console.error('Save failed', res.status, errorMessage)
        showSnack(errorMessage, 'error')
      }
    } catch (err) {
      console.error('Save error', err)
      showSnack('Save failed (network error)', 'error')
    }
  }

  const deleteMember = async (member) => {
    if (!confirm(`Delete member ${member.name}?`)) return
    try {
      const res = await fetch(`${API_BASE}/${member.id}`, { method: 'DELETE' })
      if (res.ok) {
        showSnack('Member deleted', 'success')
        await fetchMembers()
      } else {
        let errorMessage = 'Delete failed'
        try {
          const errorData = await res.json()
          if (errorData.message) {
            errorMessage = errorData.message
          }
        } catch (parseError) {
          errorMessage = `Delete failed: ${res.status} ${res.statusText}`
        }
        showSnack(errorMessage, 'error')
      }
    } catch (err) {
      console.error('Delete error', err)
      showSnack('Delete failed (network error)', 'error')
    }
  }

  return (
    <div>
      <Card sx={{ mb: 2 }}>
        <CardContent sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Typography variant="h5" color="secondary">Member Management</Typography>
          <Button variant="contained" color="primary" onClick={openAdd}>Add Member</Button>
        </CardContent>
      </Card>

      <Card>
        <CardContent>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell>ID</TableCell>
                <TableCell>Name</TableCell>
                <TableCell>Age</TableCell>
                <TableCell>Gender</TableCell>
                <TableCell>Contact</TableCell>
                <TableCell>Actions</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {members.map((m) => (
                <TableRow key={m.id}>
                  <TableCell>{m.id}</TableCell>
                  <TableCell>{m.name}</TableCell>
                  <TableCell>{m.age}</TableCell>
                  <TableCell>{m.gender}</TableCell>
                  <TableCell>{m.contact}</TableCell>
                  <TableCell>
                    <Box sx={{ display: 'flex', gap: 1 }}>
                      <IconButton size="small" onClick={() => openEdit(m)}><EditIcon /></IconButton>
                      <IconButton size="small" onClick={() => deleteMember(m)}><DeleteIcon /></IconButton>
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} fullWidth maxWidth="sm">
        <DialogTitle>{editingMember ? 'Edit Member' : 'Add Member'}</DialogTitle>
        <DialogContent>
          <Box sx={{ display: 'grid', gap: 2, mt: 1 }}>
            <TextField label="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} fullWidth />
            <TextField label="Age" type="number" value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} />
            <Select value={form.gender} onChange={(e) => setForm({ ...form, gender: e.target.value })} displayEmpty>
              <MenuItem value="">Select gender</MenuItem>
              <MenuItem value="Male">Male</MenuItem>
              <MenuItem value="Female">Female</MenuItem>
              <MenuItem value="Other">Other</MenuItem>
            </Select>
            <TextField label="Contact" value={form.contact} onChange={(e) => setForm({ ...form, contact: e.target.value })} fullWidth />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenDialog(false)}>Cancel</Button>
          <Button variant="contained" color="primary" onClick={saveMember}>{editingMember ? 'Update' : 'Add'}</Button>
        </DialogActions>
      </Dialog>

      <Snackbar open={snack.open} autoHideDuration={4000} onClose={() => setSnack({ ...snack, open: false })}>
        <Alert onClose={() => setSnack({ ...snack, open: false })} severity={snack.severity} sx={{ width: '100%' }}>{snack.message}</Alert>
      </Snackbar>
    </div>
  )
}
